### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by patricklohn** [patricklohn/blog-react-js#1]
# Criar estilização barra de rolage

Criar estilo para a Scrollbar do projeto 

## Exemplo de codigo:

```Css
/* Define a largura da barra de rolagem */
::-webkit-scrollbar {
    width: 10px; /* Para barra vertical */
    height: 10px; /* Para barra horizontal */
}

/* Cor de fundo da área da barra de rolagem */
::-webkit-scrollbar-track {
    background: #f1f1f1;
    border-radius: 5px;
}

/* Estiliza a parte que se move (thumb) */
::-webkit-scrollbar-thumb {
    background: #888;
    border-radius: 5px;
}

/* Muda a cor quando passa o mouse */
::-webkit-scrollbar-thumb:hover {
    background: #555;
}
```
